### ISSUE TITLE
Make bare (on fork)

### ISSUE THREAD

**Issue by blaggacao** [nrdxp/nixflk#100]
If anyone wants to create a quick bare variant of the latest advancements.

This seems to work:

```command
$ git show bare:mkbare.sh | zsh
```

(I'll try to find out how to do git format patch on the diff so that history will remain consistent and no force pushing is required, so that in principale #91 workflows can be supported also for bare)

**Comment by nrdxp** [comment]
I think the simplest thing to do would be to invert the flow. So instead of making template bare. We rebase template off of the bare branch, probably by clearing all profiles and modules with a given commit to make bare, then adding them back in on top of the bare repo so we can just simply rebase with `git rebase bare` from template.

**Comment by blaggacao** [comment]
Yep that sounds great! I was trying to invent something with `git filter-repo` but it failed loudly.

**Comment by Pacman99** [comment]
Does this mean bare would become the default branch for new commits?

**Comment by nrdxp** [comment]
Essentially yes, we could rename it to something like core. We'd probably also want to make it the default branch

**Comment by Pacman99** [comment]
Ohh nice, that would make it much easier to add new nixflk features to forks once you've changed things.
