### ISSUE TITLE
Upstream nixpkgs?

### ISSUE THREAD

**Issue by piotr-szegda** [nrdxp/nixflk#12]
**Is your feature request related to a problem? Please describe.**
Can I use upstream nixpkgs? Branch release-20.03 now have flake.nix. I tried to switch to it but stuck on error: "flake-registry.json' has unsupported version 2".

**Comment by nrdxp** [comment]
Yeah I was having the same issue, basically it has to do with the recent merge and some commit updates that change the registry version. If you were using this before the merge it will give you the error. Simplest fix is to simply change the nixpkgs input manually `inputs.nixpkgs.url = "github:NixOS/nixpkgs";` for a single update.

Then after the update finishes, you could just drop the input all together and just use `nixpkgs` from registry, since it is now pointing to upstream. I'm gonna be updating it myself in a bit, my machine is in the middle of updating right now. Once it is done, I'll push the commit.

**Comment by piotr-szegda** [comment]
Changing inputs.nixpkgs.url don't solve problem in my case. I had to remove inputs.home.url to build. 
If I unintended correctly your fork of home-manager is depending on your fork of nixpkgs.

**Comment by piotr-szegda** [comment]
Thanks to this commit: https://github.com/NixOS/nixpkgs/commit/e421d740cba3dbd78d5f3d592a4413237c0b0363 I was able to update the system to 20.03 but without home-manager.

How to update:

1. Change inputs.nixpkgs.url to "github:NixOS/nixpkgs/release-20.03";
2. Remove home-manager from config (I wasn't able to fix it :( )
2. Mount /nix/store in rw mode mount -o remount,rw /nix/store
3. Replace local cache of flake-registry.json (in my case nix/store/a4db1w50nsqy79xv072ijf5pi4x0g4cl-flake-registry.json) with version 1 (last working version 1 https://raw.githubusercontent.com/NixOS/flake-registry/5bfb0451bf1d527916b28112937da9382f4ecf26/flake-registry.json)
4.Update

Only left problem is broken home-manager.

**Comment by zimbatm** [comment]
Commit dd7f6b0c6b461dbc69c1b11ebcf1c8ea5b6160ec from nixpkgs contains the update nixFlake version that supported the registry v2 format.
