### ISSUE TITLE
how to use NUR?

### ISSUE THREAD

**Issue by bbigras** [nrdxp/nixflk#8]
I tried to edit my `users/bbigras2/default.nix` file like this:

```nix
{
  nurNoPkgs = import (builtins.fetchTarball {
    url = https://github.com/nix-community/NUR/archive/master.tar.gz;
    sha256 = "1fkrrkmxq69z6ai039z9ql7zyqxf3yxz4p0f34bwrz80479bz2wb";
  }) {};

# ...

  imports = [
    nurNoPkgs.repos.rycee.hmModules.emacs-init
  ];
}
```

I get:

```
error: value is a function while a set was expected, at /nix/store/ylzadblp5bl370z4n1x2y3nfd6j3phv3-source/users/bbigras2/default.nix:29:5
```

Does this count as a channel? I saw the warning about using nix-channels in the Readme but I'm not using a channel like this:
```nix
{ nurNoPkgs = import <nur> { pkgs = null; }; }
```

**Comment by nrdxp** [comment]
Hmm, I have never used NUR, but the [expression](https://github.com/nix-community/nur-combined/blob/master/repos/rycee/hm-modules/emacs-init.nix) your trying to import looks fine to me.

What's the output of `lib.traceVal` on `nurNoPkgs`.

**Comment by nrdxp** [comment]
I just made a pr to merge in NUR support. It will allow you to pull in modules from the new top-level `nurModules` attribute. Not everything will work, as some authors have hardcoded imports from the nixpath, but I tested many different modules, overlays and packages to make sure most things work.

I also made a [PR](https://github.com/nix-community/NUR/pull/175) to include this in upstream NUR.

With this you can solve your problem. Since your module is expecting `home-manager` to be named `home` instead, you could simply create a new module ./modules/home.nix:
```nix
{ options, config, ...}:
{
  options.home = options.home-manager;
  config.home = config.home-manager;
}
```
